/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check


/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lmosSidebar: [
    "introduction",
    "who_is_it_for",
    "agent",
    "tool",
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting_started', // Directory where your markdown files are stored
        },
      ],
    },
    {
      type: 'category',
      label: 'Multi-Agent System',
      link: {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'multi_agent_system/overview',
        'multi_agent_system/agent_description',
        'multi_agent_system/agent_discovery',
        'multi_agent_system/agent_registry',
        'multi_agent_system/agent_communication',
        'multi_agent_system/group_management',
        'multi_agent_system/agent_lifecycle'
      ],
    },
    {
      type: 'category',
      label: 'LMOS Protocol',
      link: {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'lmos_protocol', // Directory where your markdown files are stored
        },
      ],
    },
    {
      type: 'category',
      label: 'LMOS Platform',
      link: {
        type: 'generated-index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        'lmos_platform/overview',
        'lmos_platform/lmos_control_plane',
        'lmos_platform/lmos_router',
        'lmos_platform/lmos_runtime',
      ],
    },
  ],
  protocolSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'lmos_protocol'
    }
  ],
  arcSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'arc'
    }
  ],
};

export default sidebars;
