name: Deploy website

on:
  push:
    branches:
      - source

permissions:
  contents: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: source
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni
      - name: Install dependencies
        run: nci
      - name: Build
        run: nr build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
  deploy:    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: rm -rf ./*
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github" && git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deploy"
          git push
